### Consulta de todas las tareas
GET http://localhost:3000/todos

### Consulta de una tarea por id
GET http://localhost:3000/todos/1

### Crear una nueva tarea
POST http://localhost:3000/todos
Content-Type: application/json

{
  "titlee": "Creación de una tarea",
  "description": null,
  "author": "Juan Alvarenga",
  "fkejnwf":124,
  "isCompleted": false,
  "dueDate": "2025-05-01T00:00:00.000Z",
  "script": "<script>alert('XSS')</script>"
}